//! Cross-repo golden-vector contract.
//!
//! This test pins a FIXED table of link frames to a committed hex file
//! (`tests/golden_frames.txt`). The Rust `link` codec is the source of truth for byte exactness;
//! the Android app's Kotlin `link` codec reads the SAME file (copied into its test resources) and
//! must reproduce every `frame_hex` byte-for-byte. That makes the file the durable Kotlin <-> Rust
//! byte-agreement contract.
//!
//! File format: one vector per line, fields separated by `|`:
//!   name|opcode_hex|src|dst|payload_hex|frame_hex
//! plus a few `crc|...` anchor lines for the raw CRC-16/MODBUS check values. Lines starting with
//! `#` and blank lines are comments.
//!
//! To regenerate the file after an intentional change, run:
//!   cargo test -p link --test golden -- --ignored regenerate_golden_file
//! then review the diff. The normal `golden_matches_committed_file` test fails if the committed
//! file and the codec ever drift.

use link::frame::{encode, FrameHeader, MAX_FRAME, PROTO_VER};
use link::opcode::Opcode;
use link::payload::{DriveCmd, Inputs, Telemetry};
use link::crc16;

const GOLDEN_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden_frames.txt");

/// One pinned frame vector.
struct Vector {
    name: &'static str,
    opcode: Opcode,
    src: u8,
    dst: u8,
    payload: heapless::Vec<u8, 64>,
}

fn pv(bytes: &[u8]) -> heapless::Vec<u8, 64> {
    let mut v = heapless::Vec::new();
    v.extend_from_slice(bytes).unwrap();
    v
}

/// The fixed table of frame vectors. Order is part of the contract (the Kotlin side reads by name,
/// not index, but keeping order stable keeps the diff small).
fn vectors() -> heapless::Vec<Vector, 8> {
    let mut out: heapless::Vec<Vector, 8> = heapless::Vec::new();

    let mut inputs_payload = [0u8; Inputs::LEN];
    Inputs { throttle: -1000, buttons: 0, rider: 1 }.encode(&mut inputs_payload);
    out.push(Vector {
        name: "inputs_throttle_neg1000_rider1",
        opcode: Opcode::Inputs,
        src: 0xA0,
        dst: 0xFF,
        payload: pv(&inputs_payload),
    }).ok();

    let mut stop_payload = [0u8; Inputs::LEN];
    Inputs { throttle: 0, buttons: 0, rider: 0 }.encode(&mut stop_payload);
    out.push(Vector {
        name: "inputs_stop_zero",
        opcode: Opcode::Inputs,
        src: 0xA0,
        dst: 0xFF,
        payload: pv(&stop_payload),
    }).ok();

    let mut drive_payload = [0u8; DriveCmd::LEN];
    DriveCmd { kind: 1, value: 300, steer: 0 }.encode(&mut drive_payload);
    out.push(Vector {
        name: "drivecmd_speed_300",
        opcode: Opcode::DriveCmd,
        src: 0xA0,
        dst: 0x01,
        payload: pv(&drive_payload),
    }).ok();

    let mut telem_payload = [0u8; Telemetry::LEN];
    Telemetry {
        motor_index: 0,
        battery_mv: 36000,
        current_ca: -250,
        speed: 1200,
        fault_code: 0,
        flags: 0x01,
    }
    .encode(&mut telem_payload);
    out.push(Vector {
        name: "telemetry_motor0",
        opcode: Opcode::Telemetry,
        src: 0x01,
        dst: 0xA0,
        payload: pv(&telem_payload),
    }).ok();

    out
}

fn frame_hex(v: &Vector) -> heapless::String<256> {
    let hdr = FrameHeader {
        ver: PROTO_VER,
        opcode: v.opcode,
        src: v.src,
        dst: v.dst,
        len: v.payload.len() as u8,
    };
    let mut out = [0u8; MAX_FRAME];
    let n = encode(&hdr, &v.payload, &mut out).unwrap();
    to_hex(&out[..n])
}

fn to_hex(bytes: &[u8]) -> heapless::String<256> {
    let mut s: heapless::String<256> = heapless::String::new();
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for &b in bytes {
        s.push(HEX[(b >> 4) as usize] as char).unwrap();
        s.push(HEX[(b & 0x0F) as usize] as char).unwrap();
    }
    s
}

/// Build the full committed file content from the codec.
fn render_golden() -> String {
    let mut s = String::new();
    s.push_str("# Cross-repo golden link-frame vectors. Generated by crates/link/tests/golden.rs.\n");
    s.push_str("# Format: name|opcode_hex|src|dst|payload_hex|frame_hex\n");
    s.push_str("# CRC anchors: crc|<input_hex>|<crc16_modbus_hex>\n");
    for v in vectors() {
        let opcode_hex = format!("{:02x}", v.opcode.to_u8());
        let payload_hex = to_hex(&v.payload);
        let fh = frame_hex(&v);
        s.push_str(&format!(
            "{}|{}|{}|{}|{}|{}\n",
            v.name, opcode_hex, v.src, v.dst, payload_hex, fh
        ));
    }
    // Raw CRC-16/MODBUS anchors (the three cross-language check values).
    s.push_str(&format!("crc|{}|{:04x}\n", to_hex(b"123456789"), crc16::modbus(b"123456789")));
    s.push_str(&format!(
        "crc|{}|{:04x}\n",
        to_hex(&[0x01, 0x02, 0x03, 0x04, 0x05]),
        crc16::modbus(&[0x01, 0x02, 0x03, 0x04, 0x05])
    ));
    s.push_str(&format!("crc||{:04x}\n", crc16::modbus(&[])));
    s
}

/// The codec output must match the committed golden file exactly. This locks the Rust side: any
/// change to the frame layout, CRC, or a pinned vector fails here until the file is regenerated and
/// reviewed (and the matching change copied to the app's `golden_frames.txt`).
#[test]
fn golden_matches_committed_file() {
    let committed = std::fs::read_to_string(GOLDEN_PATH)
        .unwrap_or_else(|e| panic!("read {GOLDEN_PATH}: {e}; run the ignored regenerate test"));
    let rendered = render_golden();
    assert_eq!(
        committed, rendered,
        "committed golden file is out of date; run `cargo test -p link --test golden -- --ignored regenerate_golden_file` and review"
    );
}

/// Pin the exact hex of the headline vectors directly in the test, independent of the file, so a
/// corrupted/overwritten golden file cannot silently weaken the contract.
#[test]
fn golden_hex_literals_pinned() {
    let vs = vectors();
    // inputs throttle=-1000 rider=1: 5a 01 50 a0 ff 04 | 18 fc 00 01 | crc 5f19 LE
    assert_eq!(frame_hex(&vs[0]).as_str(), "5a0150a0ff0418fc0001195f");
    // inputs stop 0,0,0
    assert_eq!(frame_hex(&vs[1]).as_str(), "5a0150a0ff04000000001e0f");
    // drivecmd kind=1 value=300 steer=0
    assert_eq!(frame_hex(&vs[2]).as_str(), "5a0111a00105012c010000c9d5");
    // telemetry motor0
    assert_eq!(frame_hex(&vs[3]).as_str(), "5a012001a00900a08c06ffb00400013fc8");
}

/// Regenerate the committed golden file from the codec. Run with `-- --ignored` after an
/// intentional change, then review and commit the diff.
#[test]
#[ignore]
fn regenerate_golden_file() {
    std::fs::write(GOLDEN_PATH, render_golden()).unwrap();
}
